FROM bitnami/spark:3.5.0

USER root

# Installer pip et dépendances Python
RUN apt-get update && apt-get install -y python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Installer les librairies Python nécessaires
RUN pip3 install pyspark hdfs

# Créer dossier d'application
WORKDIR /app

# Copier ton script
COPY main.py .

# Commande de lancement (tout en une seule liste)
CMD ["spark-submit","--packages","org.postgresql:postgresql:42.6.0","main.py"]